### ISSUE TITLE
Failed to compile on Ubuntu14.10

### ISSUE THREAD

**Issue by hujianxin** [Golevka/emacs-clang-complete-async#85]
``` bash
hujianxin@hujianxin-Lenovo-IdeaPad-S206:/tmp/emacs-clang-complete-async$ make
cc -std=c99 -I/usr/lib/llvm-3.5/include  -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -g -O2 -fomit-frame-pointer -fPIC -Wall -Wextra -pedantic -O3 -I./src   -c -o src/obj/completion_serv.o ./src/completion_serv.c
In file included from ./src/completion_serv.c:3:0:
./src/completion.h:5:27: fatal error: clang-c/Index.h: No such file or directory
 #include <clang-c/Index.h>
                           ^
compilation terminated.
makefile.mk:43: recipe for target 'src/obj/completion_serv.o' failed
make: *** [src/obj/completion_serv.o] Error 1
```

``` bash
Ubuntu clang version 3.5.0-4ubuntu2 (tags/RELEASE_350/final) (based on LLVM 3.5.0)
Target: x86_64-pc-linux-gnu
Thread model: posix
```

``` bash
hujianxin@hujianxin-Lenovo-IdeaPad-S206:/tmp/emacs-clang-complete-async$ llvm-config --version
3.5.0

```

Can you help me find this error?

**Comment by hujianxin** [comment]
Oh my fault, just `apt-get install libclang-dev`
